---
title: fabgrid
subtitle: Low Voltage Power Grid
description: FabAcademy 2017 by Joseph Paul
baseurl: ''

status: In Preparation
status-color: info

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - docs.gemspec
  - build.sh
  - node_modules

# TypeScript config
tsc: /usr/local/bin/tsc
js_dest: assets/js